package lib

const STATUS_SUCCESS = "000000"

const BIZ_OTP_VERIFIED_FAILED = "200001"
const BIZ_SEND_SMS_FAILED = "200002"
const BIZ_WRONG_MOBILE_NUMBER = "200003"
const BIZ_REQUIRED_LOVCODE = "200004"
const BIZ_REQUIRED_CATEGORYKEY = "200005"
const BIZ_REQUIRED_TRANSACTIONID = "200006"
const BIZ_NO_RECORD = "200007"

const ERROR_JSON_UNMARSHAL_FAILED = "300001"
const ERROR_JSON_MARSHAL_FAILED = "300002"
const ERROR_SEND_SMS_FAILED = "300003"
const ERROR_NO_LOV_DATA = "300004"
const ERROR_MYSQL_QUERY_FAILED = "300005"
const ERROR_MYSQL_UPDATE_FAILED = "300006"
const ERROR_TOKEN_NOT_VERIFIED = "300007"

//LOV Code
//材料分类
const LOV_MATERIAL_CATEGORY = "MATERIAL_CATEGORY"

//材料等级
const LOV_STANDARD_TYPE = "STANDARD_TYPE"

//商户类型
const LOV_MERCHANT_TYPE = "MERCHANT_TYPE"

//餐厅
const LOV_MERCHANT_KEY_RET = "RET"

//菜老板
const LOV_MERCHANT_KEY_SUP = "SUP"

//订单类型
const LOV_TRANSACTION_TYPE = "TRANSACTION_TYPE"

//订单状态
const LOV_TRANSACTION_TYPE_START = "001"
const LOV_TRANSACTION_TYPE_NOT_PAIED = "002"
const LOV_TRANSACTION_TYPE_PAIED = "003"
const LOV_TRANSACTION_TYPE_TRANSPORT = "004"
const LOV_TRANSACTION_TYPE_SIGNOFF = "005"
const LOV_TRANSACTION_TYPE_FINISH = "006"
const LOV_TRANSACTION_TYPE_CANCEL = "007"

//Supplier Priority: 可以合作的级别
const SUPPLIER_READY = 5

//Supplier Priority: 备选送货
const SUPPLIER_QUALIFIED = 10

//REQ: 询价单
//RES: 报价单
//TRX: 订单
const ORDER_REQUEST = "REQ"
const ORDER_RESPONSE = "RES"
const ORDER_TRANSACTION = "TRX"
